apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-metrics-gs
  labels:
    application: prometheus-metrics-gs
spec:
  template:
    metadata:
      labels:
        build: v202303021127
