apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics-gs
  labels:
    application: prometheus-metrics-gs
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    application: prometheus-metrics-gs
  sessionAffinity: None
status:
  loadBalancer: { }
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics-gs-np
  labels:
    application: prometheus-metrics-gs
spec:
  type: NodePort
  selector:
    application: prometheus-metrics-gs
  ports:
    - port: 8080
      targetPort: 8080
status:
  loadBalancer: { }